**EJERCICIOS**

Use funciones o procedimientos (varias líneas) de R para responder cada una de las siguientes preguntas.













1- Construya un vector con la primeras 20 letras MAYÚSCULAS usando la función List item LETTERS.

In [ ]:
letras <- c(LETTERS[1:20]) 
lista <- letras
lista

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T"

2- Construya una matriz de 10×10 Con los primeros 100 números positivos pares.

In [ ]:
tabla1 <- matrix(data=1:100, nrow=10, ncol=10, byrow=FALSE)
tabla1_1 <- matrix(data=1:100, nrow=10, ncol=10, byrow=TRUE)

nombre_tabla1 <- c("Matriz 10x10, número positivos del 1 al 100, entrada por columna")
nombre_tabla1
tabla1

nombre_tabla1_1 <- c("Matriz 10x10, número positivos del 1 al 100, entrada por fila")
nombre_tabla1_1
tabla1_1


[1] "Matriz 10x10, número positivos del 1 al 100, entrada por columna"

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1   11   21   31   41   51   61   71   81    91  
 [2,]  2   12   22   32   42   52   62   72   82    92  
 [3,]  3   13   23   33   43   53   63   73   83    93  
 [4,]  4   14   24   34   44   54   64   74   84    94  
 [5,]  5   15   25   35   45   55   65   75   85    95  
 [6,]  6   16   26   36   46   56   66   76   86    96  
 [7,]  7   17   27   37   47   57   67   77   87    97  
 [8,]  8   18   28   38   48   58   68   78   88    98  
 [9,]  9   19   29   39   49   59   69   79   89    99  
[10,] 10   20   30   40   50   60   70   80   90   100

[1] "Matriz 10x10, número positivos del 1 al 100, entrada por fila"

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9    10  
 [2,] 11   12   13   14   15   16   17   18   19    20  
 [3,] 21   22   23   24   25   26   27   28   29    30  
 [4,] 31   32   33   34   35   36   37   38   39    40  
 [5,] 41   42   43   44   45   46   47   48   49    50  
 [6,] 51   52   53   54   55   56   57   58   59    60  
 [7,] 61   62   63   64   65   66   67   68   69    70  
 [8,] 71   72   73   74   75   76   77   78   79    80  
 [9,] 81   82   83   84   85   86   87   88   89    90  
[10,] 91   92   93   94   95   96   97   98   99   100

3- Construya una matriz identidad de dimension  3×3. Recuerde que una matriz identidad tiene sólo unos en la diagonal principal y los demás elementos son cero.

In [ ]:
identidad <- diag(3)
identidad

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

4- Construya una lista con los anteriores tres objetos creados.

In [ ]:
lista_madre <- list(lista,tabla1,identidad)
lista_madre

[[1]]
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T"

[[2]]
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    1   11   21   31   41   51   61   71   81    91
 [2,]    2   12   22   32   42   52   62   72   82    92
 [3,]    3   13   23   33   43   53   63   73   83    93
 [4,]    4   14   24   34   44   54   64   74   84    94
 [5,]    5   15   25   35   45   55   65   75   85    95
 [6,]    6   16   26   36   46   56   66   76   86    96
 [7,]    7   17   27   37   47   57   67   77   87    97
 [8,]    8   18   28   38   48   58   68   78   88    98
 [9,]    9   19   29   39   49   59   69   79   89    99
[10,]   10   20   30   40   50   60   70   80   90   100

[[3]]
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

5- Construya un marco de datos o data frame con las respuestas de 3 personas a las preguntas: (a) ¿Cuál es su edad en años? (b) ¿Tipo de música que más le gusta? (c) ¿Tiene usted pareja sentimental estable?

In [ ]:
edad <- c(57,21,25)
musica <- c('jazz','indie','R&B')
pareja <-c(TRUE,FALSE,TRUE)

df_1 <- data.frame(edad,musica,pareja)
df_1


edad musica pareja
1 57   jazz    TRUE 
2 21   indie  FALSE 
3 25   R&B     TRUE

6- ¿Cuál es el error al correr el siguiente código? ¿A qué se debe?

    edad <- c(15, 19, 13, NA, 20)
    deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
    comic_fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')
    matrix(edad, deporte, comic_fav)

    
# RESPUESTA PUNTO 6:    

**ANTES DE CONSTRUIR LA MARIZ ES NECESARIO UNIR LOS VECTORES, LUEGO ESTRUCTURAR LA MATRIZ (DATOS, FILAS, COLUMNAS, ENTRADA)**

In [ ]:
edad <- c(15, 19, 13, NA, 20)
deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
comic_fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')
datos <- c(edad,deporte,comic_fav)   #UNIMOS VECTORES
matriz3 <- matrix(data=datos, nrow = 5, ncol=3, byrow = FALSE)  #ESTRUCTURAMOS LA MATRIZ

colnames(matriz3)<-c("EDAD","DEPORTE","COMIC")   #NOMBRAMOS LAS COLUMNAS
matriz3



EDAD DEPORTE COMIC   
[1,] 15   TRUE    NA      
[2,] 19   TRUE    Superman
[3,] 13   NA      Batman  
[4,] NA   FALSE   NA      
[5,] 20   TRUE    Batman

In [ ]:
#solución apilando listas
edad <- c(15, 19, 13, NA, 20)
deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
comic_fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')


matriz_sin_error1 <- matrix(c(15, 19, 13, NA, 20), ncol = 5, byrow = TRUE)
matriz_sin_error2 <- matrix(c(TRUE, TRUE, NA, FALSE, TRUE), ncol = 5, byrow = TRUE)
matriz_sin_error3 <- matrix(c(NA, 'Superman', 'Batman', NA, 'Batman'), ncol = 5, byrow = TRUE)

rownames(matriz_sin_error1) <- c("EDAD")
rownames(matriz_sin_error2) <- c("DEPORTE")
rownames(matriz_sin_error3) <- c("COMIC")

rbind (matriz_sin_error1,matriz_sin_error2,matriz_sin_error3)


[,1] [,2]     [,3]   [,4]  [,5]  
EDAD    15   19       13     NA    20    
DEPORTE TRUE TRUE     NA     FALSE TRUE  
COMIC   NA   Superman Batman NA    Batman

In [ ]:
#Solución almacenando variables
x <- cbind(edad, deporte, comic_fav)
x

edad deporte comic_fav
[1,] 15   TRUE    NA       
[2,] 19   TRUE    Superman 
[3,] 13   NA      Batman   
[4,] NA   FALSE   NA       
[5,] 20   TRUE    Batman